export const PKG_PREFIX = '@meng-ui-vue'
export const PKG_NAME = 'meng-ui-vue'
export const PKG_CAMELCASE_NAME = 'MenguiVue'
export const PKG_CAMELCASE_LOCAL_NAME = 'MengUILocale'
export const PKG_BRAND_NAME = 'MengUI'
