export const PKG_PREFIX = '@mengui-vue'
export const PKG_NAME = 'mengui-vue'
export const PKG_CAMELCASE_NAME = 'MenguiVue'
export const PKG_CAMELCASE_LOCAL_NAME = 'MengUILocale'
export const PKG_BRAND_NAME = 'MengUI'
